#include "stm32l1xx.h"
#include "stm32l1xx_hal.h"

/* Handles interrupts generated by pressing the USER button.  */
void HAL_GPIO_EXTI_Callback(uint16_t GPIO_Pin)
{
	HAL_GPIO_TogglePin(GPIOB, GPIO_PIN_7);
	//EXTI_ClearITPendingBit( EXTI_Line0 );
}
